### ISSUE TITLE
Problem with shadows in 3D scenes

### ISSUE THREAD

**Issue by Wuan23** [Antoshidza/NSprites#17]
Great performance, but there is a problem. In the 3D scene, (You may find this a little strange, but it is very important for 2.5D games) after creating the light source and the plane, turn on the shadow and you will see a huge circular shadow cast on the plane, which will not appear if you do not use NSprite rendering. In fact, if you adjust the shadow distance to infinity, you can find that the entire ground is covered in shadows.

**Comment by Wuan23** [comment]
![屏幕截图 2024-06-03 130551](https://github.com/Antoshidza/NSprites/assets/126873164/47f020a9-7302-4c20-b261-4a9d71758d7f)

**Comment by Antoshidza** [comment]
`NSprites-Foundation` implements shader for 2D use only, if you need 2.5D you should implement shader which account lightning and shadows and also probably strip out sorting logic because in 3D we have depth.

So the answer is: it shouldn't be used within 3D environment and also NSprites itself is just CPU->GPU sync tool and has nothing to do with concrete shaders.
