### ISSUE TITLE
RenderArchetype.cs has wrong encoding on macOS and invalid characters

### ISSUE THREAD

**Issue by lukasreuter** [Antoshidza/NSprites#4]
Opening the sample project or trying to use the package on macOS (tested on M1 Pro, macOS Monterey) fails to compile and shows multiple errors in the console like: "Library/PackageCache/com.tonymax.nsprites@aedf3b99f0/Rendering/Common/RenderArchetype.cs(205,71): error CS1519: Invalid token '�' in class, record, struct, or interface member declaration"

converting the encoding in Rider for example to UTF8 does not fix the issue.

edit: seems to be the "C" character in "ChunkBaseEntityIndices" is invalid/corrupted

**Comment by Antoshidza** [comment]
Hi @lukasreuter! Thank you for opening this issue!
I was facing this problem some time ago and yes - the problem exactly in letter `C` (I did multiple mistake because in my native language alphabet there is same looking letter `С` which sounds like `S` in eng).
I saw that even github prints such token '�' but I've fixed that in some commit so now can't see this token.
Have you working with latest version? If yes since I can't test it on macOS can you please help me and give an advice of how can I detect wrong symbols?
